import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Header from "../../layouts/Header/Header.jsx";
import React from "react";

export const metadata = {
  title: "argaam weekend",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { lang } = await params;
  
  return (
    <html lang={lang} dir={lang === "ar" ? "rtl" : "ltr"}>
      <body>
        <div className="fixed-width mt-5">
          <Header lang={lang} />
          {children}
        </div>
      </body>
    </html>
  );
}
