export const metadata = {
  title: "argaam",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
    </html>
  );
}
